.TH "freedcpp" 1 "17 Mar 2019"
.SH "NAME"
freedcpp \- file sharing program using DC and ADC protocols
.SH "SYNOPSIS"
.PP
.B freedcpp
.SH "DESCRIPTION"
.PP
\fBFreeDC++\fP is a program for UNIX-like systems that uses the Direct Connect and Advanced Direct Connect protocols. It is compatible with DC++, EiskaltDC++, FlylinkDC++, LinuxDC++ and other DC clients. FreeDC++ also interoperates with all common DC hub software.
.PP
FreeDC++ is based on LinuxDC++ source code, but now it noticeably differs from it.
.SH "COMMAND LINE OPTIONS"
.RB "This program does not have command line options yet."
.SH "FILES"
.TP
.B "~/.dc++/"
Directory with user configuration files.
.SH "BUG REPORTS"
If you find a bug in FreeDC++ please report it here:
.B https://github.com/eiskaltdcpp/freedcpp/issues
