# -*- coding: utf-8 -*-

# todo: Replace this with env.Glob('*.cpp') when Scons 0.98 is widespread enough 
# (glob.glob() doesn't work here due to the use of a variant dir).
gui_files = [
	'bookentry.cc',
	'dialogentry.cc',
	'downloadqueue.cc',
	'entry.cc',
	'favoritehubs.cc',
	'finishedtransfers.cc',
	'hashdialog.cc',
	'hub.cc',
	'mainwindow.cc',
	'privatemessage.cc',
	'publichubs.cc',
	'search.cc',
	'settingsdialog.cc',
	'settingsmanager.cc',
	'sharebrowser.cc',
	'treeview.cc',
	'UserCommandMenu.cc',
	'wulfor.cc',
	'wulformanager.cc',
	'WulforUtil.cc']

Import('env')

# We don't want to add these CFLAGS globally so we copy the env
env = env.Clone()
env.ParseConfig('pkg-config --cflags libglade-2.0')

# Build the gui_files
obj_files = env.Object(gui_files)

Return('obj_files')

